---
name: {{role_name}}-init
description: "{{role_name}} 初始化（AgentCharter charter v{{charter_version}}、vendor Codex Desktop）。Use when the user asks Codex to run {{role_name}} init or mentions /{{role_name}}-init."
---

<!--
Codex Desktop Vendor Adapter — Skill schema（SKILL.md 固定檔名 + name/description frontmatter）

Generated by: AgentCharter v0.12.0 vendor adapter
Source: ~/.agentcharter/roles/{{role_name}}/init-spec.md (canonical)
Adapter: ~/.agentcharter/templates/vendor-adapters/codex.skill.tpl
Target: ~/.codex/skills/{{role_name}}-init/SKILL.md

Schema 規範：~/.agentcharter/roles/engineer/codex.md §4.1
Native slash command note: current Codex Desktop local inspection did not verify a .codex/commands/ mechanism; this adapter targets Codex Skills.
-->

# {{role_name}} 初始化（Codex Desktop）

你現在扮演 {{role_name}} 角色：

- charter v{{charter_version}}
- vendor tool：Codex Desktop / Codex CLI
- vendor adapter：Codex Skill (`~/.codex/skills/{{role_name}}-init/SKILL.md`)

依 `~/.agentcharter/core/init-spec-schema.md` 6 段 + `~/.agentcharter/roles/{{role_name}}/init-spec.md` canonical 執行。此 adapter 只做 canonical → Codex Skill 格式轉換，不增減 Step 0-5 邏輯。

## Step 0：Pre-Init（歷史學習迴圈）

MUST 讀取：

1. `<common_memory_root>/roles/{{role_name}}/reflections/*.md`
2. `<common_memory_root>/state/failure_mode_log.md`（最近 10 條）
3. `<common_memory_root>/institutional-memory/_root.md`

{{step_0_content}}

## Step 1：Load（協議載入）

MUST 讀全文：

- `roles/{{role_name}}/_spec.md`
- `roles/{{role_name}}/init-spec.md`
- `roles/{{role_name}}/codex.md`
- `templates/vendor-adapters/codex.skill.tpl`

{{step_1_content}}

## Step 2：Mental Anchors（10 條心智守則）

依 `roles/{{role_name}}/_spec.md §5` + `roles/{{role_name}}/init-spec.md Step 2`：

{{step_2_content}}

## Step 3：Environment Snapshot

工具以 Codex shell / file read 能力具象化；Windows session 可用 PowerShell，其他平台依 shell 等價轉換：

- `Get-Content <common_memory_root>/state/output_mode_file`
- `Get-ChildItem <common_memory_root>/handoffs`
- `git status --short`
- `git log --oneline -10`

若可用，額外檢查 Codex feature / vendor 狀態：

- `codex features list`
- `Get-ChildItem ~/.codex/skills`
- `Get-ChildItem ~/.codex/plugins`

{{step_3_content}}

## Step 4：Audit State

- 讀 `<common_memory_root>/state/audit_state.md`
- 對齊 `core/audit-rights.md` + `core/escalation-protocol.md`
- 對 PM 結案宣告以 `Get-ChildItem` / `rg -n` / `git log` / 親跑測試抽驗

{{step_4_content}}

## Step 5：Ready Report

依 `roles/{{role_name}}/init-spec.md Step 5` 統一輸出格式，並標明 vendor Codex Desktop。

{{step_5_content}}

## Step 5+：Vendor-specific extensions（Codex Desktop）

⚠️ Codex Skill 不是 native slash command：
- 本 adapter 產物是 `~/.codex/skills/{{role_name}}-init/SKILL.md`
- 若 user 說 `/{{role_name}}-init`，Codex 應把它視為執行本 skill 的意圖，而非宣稱 `.codex/commands/` 已存在
- 若採用方需要真正 slash-like source command bridge，必須由 user 明示授權後另行建立

⚠️ Sub-agent / multi-agent 跨界禁令：
- 只有 user 明示要求 delegation / sub-agent 時才可使用
- 不可派 sub-agent 寫 PM capsule / handoff / protocols 或代行結案
- sub-agent 結果必由主 Codex Engineer 抽驗後才可納入 VCP

⚠️ Codex vendor 預設行為自防：
- plugins / skills / hooks / approval rules 只作工具，不取代 charter 角色邊界
- 找不到 `roles/{{role_name}}/codex.md` 時只讀 `_spec.md` 概念層，不 fallback 讀其他 vendor spec
- session resume / fork 後仍須重新讀 common-memory-root，不依賴隱性 memory
