# Gemini CLI Vendor Adapter — flat TOML schema
#
# Generated by: AgentCharter v0.12.0 vendor adapter
# Source: ~/.agentcharter/roles/{{role_name}}/init-spec.md (canonical)
# Adapter: ~/.agentcharter/templates/vendor-adapters/gemini-cli.toml.tpl
# Target: <project>/.gemini/commands/{{role_name}}-init.toml
#
# Schema 規範：~/.agentcharter/roles/pm/gemini-cli.md §3.6（flat TOML、禁 name 欄位）
# vendor_status: LEGACY_AUTO_IMPORTED（Gemini CLI 2026-06-18 對 Pro/Ultra/free 斷線）

description = "{{role_name}} 初始化（AgentCharter charter v{{charter_version}}、vendor Gemini CLI）"

prompt = """
你現在扮演 {{role_name}} 角色（charter v{{charter_version}}、vendor Gemini CLI）。

依 ~/.agentcharter/core/init-spec-schema.md 6 段 required sections + ~/.agentcharter/roles/{{role_name}}/init-spec.md canonical 執行：

## Step 0: Pre-Init（歷史學習迴圈）
{{step_0_content}}

## Step 1: Load
{{step_1_content}}

## Step 2: Mental Anchors
{{step_2_content}}

## Step 3: Environment Snapshot
{{step_3_content}}

## Step 4: Audit State
{{step_4_content}}

## Step 5: Ready Report
{{step_5_content}}

## Step 5+: Vendor-specific extensions（Gemini CLI）

⚠️ 必對採用方提醒：Gemini CLI 預設 `generalist` agent 自動分包繞 PM 卡控（dogfood signal #55、charter v0.10.5 紀律）。建議現在執行：

```
/agents disable generalist
```

對齊 core/role-separation §3.5 卡控紀律。已執行請告知。

⚠️ Vendor LEGACY 警告：Gemini CLI 2026-06-18 對 Google AI Pro / Ultra / 個人免費版斷線。若你在這些 tier、請依 examples/upgrades/v0.10.6-to-v0.12.0-antigravity-canonical-rename.md walkthrough 遷移到 Antigravity CLI。
"""
